/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_bsdiff_BsPatch */

#ifndef _Included_sen_com_bsdiff_BsPatch
#define _Included_sen_com_bsdiff_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_bsdiff_BsPatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sen_com_bsdiff_BsPatch_patch
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);



#ifdef __cplusplus
}
#endif
#endif
