/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_dnstudyffmpeg01_NdkTest */

#ifndef _Included_sen_com_dnstudyffmpeg01_NdkTest
#define _Included_sen_com_dnstudyffmpeg01_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_dnstudyffmpeg01_NdkTest
 * Method:    diffFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_sen_com_dnstudyffmpeg01_NdkTest_diffFile
  (JNIEnv *, jobject, jstring, jstring,jstring, jint);

/*
 * Class:     sen_com_dnstudyffmpeg01_NdkTest
 * Method:    patchFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_sen_com_dnstudyffmpeg01_NdkTest_patchFile
  (JNIEnv *, jobject, jstring, jstring,jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
